version: 2

models:
  - name: category
    description: "Table RAW des catégories de livres"
    columns:
      - name: id
        tests: [unique, not_null]
      - name: intitule
      - name: created_at

  - name: books
    description: "Table RAW des livres"
    columns:
      - name: id
        tests: [unique, not_null]
      - name: category_id
      - name: code
      - name: intitule
      - name: isbn_10
      - name: isbn_13
      - name: created_at

  - name: customers
    description: "Table RAW des clients"
    columns:
      - name: id
        tests: [unique, not_null]
      - name: code
      - name: first_name
      - name: last_name
      - name: created_at

  - name: factures
    description: "Table RAW des factures"
    columns:
      - name: id
        tests: [unique, not_null]
      - name: code
      - name: date_edit
      - name: customers_id
      - name: qte_totale
      - name: total_amount
      - name: total_paid
      - name: created_at

  - name: ventes
    description: "Table RAW des ventes"
    columns:
      - name: id
        tests: [unique, not_null]
      - name: code
      - name: date_edit
      - name: factures_id
      - name: books_id
      - name: pu
      - name: qte
      - name: created_at
