name: 'bookshop'
version: '1.0'
config-version: 2

profile: 'bookshop'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

tests:
  bookshop:
    staging:
      +enabled: false
    warehouse:
      +enabled: false
    marts:
      +enabled: false
    
models:
  bookshop:
    staging:
      materialized: table
      schema: STAGGING
    warehouse:
      materialized: table
      +schema: WAREHOUSE
    marts:
      materialized: table
      +schema: MARTS