name: 'bookshop'
version: '1.0'
config-version: 2

profile: 'bookshop'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
seeds:
  bookshop_dbt:
    schema: raw
    quote_columns: true
    
models:
  bookshop:
    staging:
      materialized: table
      schema: staging
    warehouse:
      materialized: table
      schema: warehouse
    marts:
      materialized: table
      schema: marts