bookshop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ...
      user: ...
      password: ....
      role: ...              
      database: BOOKSHOP
      warehouse: COMPUTE_WH
      schema: ...
      threads: 10
      client_session_keep_alive: False
